default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  host: databasehost

development:
  <<: *default
  username: root
  password: root
  database: sample_development

test:
  <<: *default
  username: root
  password: root
  database: sample_test

production:
  <<: *default
  username: root
  password: root
  database: sample_production
